### PR TITLE
refactor(chore/fonts): dissociation of the font configuration file for implement it in LMFRsite

### PR DESCRIPTION
**Pull request by marineFabien**
…be equal with LMFR

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/adeo/design-system--styleguide/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number:
https://design-system-adeo.atlassian.net/browse/MZC-98
https://design-system-adeo.atlassian.net/browse/MZC-99

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

### CODE REVIEW

**Comment by marineFabien** [comment]
> If you do that you need to change it in all previews as well.
> CR from Hollidays ;)



> If you do that you need to change it in all previews as well.
> CR from Hollidays ;)

Why ? I splited it in two setting files, and they are both imported in the all-settings file, so i don't understand your review

**Comment by gael-boyenval** [comment]
@marineFabien sorry I did not saw that. I remembered that Mélanie wanted that no font should be imported when importing the `all-settings` files. So I figured that you did not add it into the main file. My bad. Going back to my Hollidays.

**Comment by marineFabien** [comment]
I have to admit, you're right, it's the better way to implement it on LMFRsite ;)

**Comment by gael-boyenval** [comment]
@marineFabien , I think the best way is to create a mixin, that way we can use parameters to customize it the way LMFR want it and we don't have a separated file to import, and a team that do not want to implement it at all as nothing to do as well.

**Pull request closed without merging**
