### PR TITLE
docs(configuration): add documentation about mozaic.config.js

### PR DESCRIPTION
**Pull request by AdeoRemiDoolaeghe**
## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [x] No

## Describe the changes

Explains how to define the Mozaic configuration file, depending on your module system (ESM/CommonJS)

GitHub issue number or Jira issue URL: N/A

## Other information

I'm clearly open to changes, as I had to make choices on my own that could not fit very well with the Mozaic way. Don't hesiate to propose changes

### CODE REVIEW

**Review by dmartinds — COMMENTED** [review]
🎯 suggestion
It would be less confusing to add the paragraph about the different types of config files before the title and link to the [official node documentation](https://nodejs.org/api/packages.html#determining-module-system).

And keep a "default" configuration file type (`mozaic.config.js` ?), as most people copy and paste the name of the file and content of examples to start their configuration.

What do you think about it ?

**Comment by AdeoRemiDoolaeghe** [comment]
That's a good idea to rethink how it is organized.

As I'm not sure to understand precisely what you meant, I'll try to rephrase, so you can confirm or not.

Your suggestion is adding a new paragraph before the one called `mozaic.config.js` to explain the two modules systems, and how it impacts the naming of the file. Then, keep the rest of the documentation as before. Is that it?

**Comment by dmartinds** [comment]
exactly what you said @AdeoRemiDoolaeghe 👍

**Comment by AdeoRemiDoolaeghe** [comment]
I've made a new proposition. Don't hesitate to propose changes this time too.

**Review by dmartinds — APPROVED** [review]

**Pull request merged**
