### PR TITLE
feat(patterns/hero): allow the use of a fixed or fluid container

### PR DESCRIPTION
**Pull request by tiloyi**
## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes
- [ ] No

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [ ] Yes
- [x] No

## Describe the changes

Allow the use of a fixed or fluid container

GitHub issue number or Jira issue URL: N/A

### CODE REVIEW

**Comment by nherwegh** [comment]
@tiloyi just went through all the breakpoint for the fixed container. The `xl-large` case (1680px) seems a bit far left but I suppose this is a value we use already?

**Review by marineFabien — COMMENTED** [review]
the code is all right for me, but i see screen width issue with the container. Regarding the LM container we can see a

**Comment by tiloyi** [comment]
> or exemple **the container width** for superi

Hello @marineFabien ,
I understand the problem you're bringing up.
I think I know where the problem comes from, I just did a quick-fix on this PR. I'll let you check it and tell me if the behavior of the component is better now?

**Comment by tiloyi** [comment]
> The code is all right for me, but i see a screen width issue with the container. I explain myself, the Mozaic containers include paddings unlike LM containers.
> For exemple **the container width** for superior xl viewport is not a width of `1216px` with two external margins of `32px`, like it is noted in documentation, but a width of `1152px` with two paddings of `32px`.
> We can see that together next monday, if you want ?
> The documentation about it: http://mozaic.adeo.cloud/Foundations/Layout/Container/

Hello @marineFabien ,
I understand the problem you're bringing up.
I think I know where the problem comes from, I just did a quick-fix on this PR. I'll let you check it and tell me if the behavior of the component is better now?

**Review by nherwegh — APPROVED** [review]

**Review by marineFabien — APPROVED** [review]

**Pull request merged**
