### PR TITLE
feat(contributing): add configuration for all-contributors

### PR DESCRIPTION
**Pull request by C0ZEN**
## I have read [the contributing guidelines](https://mozaic.adeo.cloud/Contributing/)

- [x] Yes

## Does this PR introduce a [breaking change](https://mozaic.adeo.cloud/Contributing/Developers/GitConventions/#breaking-changes-)?

- [x] No

## Describe the changes

Add the contributors entry in the `package.json`.
Add a configuration file for all-contributors bot.
Add a new section in the `README.md` to contains the contributors.

## Other information

Related to #532.

### CODE REVIEW

**Comment by mohamedMok** [comment]
@C0ZEN  Do we need to install the all-contributors on this repository?

**Comment by C0ZEN** [comment]
@mohamedMok yes.
See https://github.com/adeo/mozaic-design-system/issues/532#issuecomment-624825558.
The GitHub app should be added to ask the bot to do stuff for you.

**Comment by mohamedMok** [comment]
The app is installed @C0ZEN!
On your branch, I can't see the changes on the readme. 
https://github.com/C0ZEN/mozaic-design-system/tree/feature/all-contributors

Your profile should show up?

**Comment by C0ZEN** [comment]
@mohamedMok I was not aware of the installation.
And no, the Readme should not for now have a list of contributors.
I was waiting the adding of the GitHub app to ask the bot to add contributors.
Also I prefer to let you handle this part of the job since I do not know which contributor should be added and for which "role".
Nevertheless, you can proceed with this merge request to merging it to add the configuration for the bot on the master branch.
Once done, you can ask the bot the add some contributors.
Sounds good to you?

**Comment by mohamedMok** [comment]
Yes thanks it all make sense! 
I'll take care of it on a new branch

**Pull request merged**
